name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout calc code
      uses: actions/checkout@v4

    - name: Install Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_LOGIN}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build and push the Docker image
      run: |
          commit_id=$(git rev-parse --short HEAD)
          image="${{secrets.DOCKERHUB_LOGIN}}/calc:$commit_id"
          docker build --tag "$image" .
          docker push "$image"
          
    - name: Tag Docker image as latest
      run: |
        commit_id=$(git rev-parse --short HEAD)
        image="${{secrets.DOCKERHUB_LOGIN}}/calc:$commit_id"
        latest_image="${{secrets.DOCKERHUB_LOGIN}}/calc:latest"
        docker tag "$image" "$latest_image"
        docker push "$latest_image"
 
